### ISSUE TITLE
Decide on db schema

### ISSUE THREAD

**Issue by kolja-lucht** [kalicalendar/community-calendar#1]
<img width="623" alt="db_schema" src="https://user-images.githubusercontent.com/6205839/56983332-ac78da80-6b83-11e9-9a89-d742a4fc6792.png">
This is the db schema we decided on. Follow up ticket for creating the db and migrations: #4 & #5

**Comment by kolja-lucht** [comment]
@clstrex Do you have any questions about the schema? If you're ok with it, you can move the ticket to the `done` column on the project board

**Comment by clstrex** [comment]
Hi! Looks fine to me. I don't understand a lot about database structures, so I can't say much about it. I only have one question: does the start and end date of the events include the time?
