### ISSUE TITLE
Saved event date doesn't show up when editing an existing event

### ISSUE THREAD

**Issue by kolja-lucht** [kalicalendar/community-calendar#108]
**Current Behavior**
Click edit for an existing event. The start and end time fields stay empty.

**Expected Behavior**
They should load the previously saved times

**Screenshot:**

<img width="897" alt="Screenshot 2020-07-29 at 20 05 39" src="https://user-images.githubusercontent.com/6205839/88836970-db8f5900-d1d7-11ea-98db-545e1de9f07f.png">

**Comment by annesbln** [comment]
This bug has been fixed in #103 However, somehow this PR has never been merged... :octocat:
