### ISSUE TITLE
Structure of the page with header and footer is improved

### ISSUE THREAD

**Issue by annesbln** [kalicalendar/community-calendar#110]
**Attention: Is only relevant after #68 is closed!!!**

**steps to reproduce:**
Open the main page

**result:**
The div for the main text body (between header and footer) sits at the very bottom (right above the footer)

**expected behavior:**
The div for the main text body (between header and footer) sits right below the header

**solution:**
CSS grid or flex box?

**Comment by kolja-lucht** [comment]
pretty much solved already 😁
