### ISSUE TITLE
Add Readmes

### ISSUE THREAD

**Issue by annesbln** [kalicalendar/community-calendar#77]
Main Readme:
- [x] What is this about?
- [x] Link zu readme for contributors

Readme for contributors:
- [ ] How to clone
- [ ] How to set-up
- [x] Link zu Coc

...

**Comment by yakamozzz** [comment]
archived:

[README_old.txt](https://github.com/ruby-stars/community-calendar/files/3774628/README_old.txt)

**Comment by yakamozzz** [comment]
...das mit dem sternchen vor kali machts im readme entweder kursiv bis zum naechsten sternchen oder versteht es als aufzaehlungspunkt... :-D
